version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
    network_mode: host

  omnidb:
    image: taivokasper/omnidb
    ports:
      - "8080:8080"
      - "25482:25482"
    volumes:
      - config-omnidb:/etc/omnidb
    network_mode: host

volumes:
  config-omnidb:
  db-data:
